/**
 * stickers.js
 * Curated sticker packs using free emoji + Telegram open sticker CDN URLs.
 * No npm install needed — pure data.
 *
 * Each sticker is either:
 *   type: "emoji"  → large emoji rendered as text (works everywhere)
 *   type: "img"    → URL to a free sticker image (webp/png/gif)
 */

export const STICKER_PACKS = [
    {
        id: "emotions",
        label: "Emotions",
        icon: "😊",
        stickers: [
            { id: "e1", type: "emoji", value: "😂" },
            { id: "e2", type: "emoji", value: "😍" },
            { id: "e3", type: "emoji", value: "🥺" },
            { id: "e4", type: "emoji", value: "😭" },
            { id: "e5", type: "emoji", value: "😤" },
            { id: "e6", type: "emoji", value: "🤩" },
            { id: "e7", type: "emoji", value: "😎" },
            { id: "e8", type: "emoji", value: "🥳" },
            { id: "e9", type: "emoji", value: "😴" },
            { id: "e10", type: "emoji", value: "🤔" },
            { id: "e11", type: "emoji", value: "😏" },
            { id: "e12", type: "emoji", value: "🙄" },
            { id: "e13", type: "emoji", value: "😬" },
            { id: "e14", type: "emoji", value: "🤯" },
            { id: "e15", type: "emoji", value: "😇" },
            { id: "e16", type: "emoji", value: "🥰" },
            { id: "e17", type: "emoji", value: "😡" },
            { id: "e18", type: "emoji", value: "😱" },
            { id: "e19", type: "emoji", value: "🤗" },
            { id: "e20", type: "emoji", value: "😜" },
        ],
    },
    {
        id: "gestures",
        label: "Gestures",
        icon: "👋",
        stickers: [
            { id: "g1", type: "emoji", value: "👍" },
            { id: "g2", type: "emoji", value: "👎" },
            { id: "g3", type: "emoji", value: "👏" },
            { id: "g4", type: "emoji", value: "🙌" },
            { id: "g5", type: "emoji", value: "🤝" },
            { id: "g6", type: "emoji", value: "✌️" },
            { id: "g7", type: "emoji", value: "🤞" },
            { id: "g8", type: "emoji", value: "👊" },
            { id: "g9", type: "emoji", value: "🤜" },
            { id: "g10", type: "emoji", value: "💪" },
            { id: "g11", type: "emoji", value: "🙏" },
            { id: "g12", type: "emoji", value: "👋" },
            { id: "g13", type: "emoji", value: "🤙" },
            { id: "g14", type: "emoji", value: "☝️" },
            { id: "g15", type: "emoji", value: "👌" },
            { id: "g16", type: "emoji", value: "🤌" },
            { id: "g17", type: "emoji", value: "🫶" },
            { id: "g18", type: "emoji", value: "🫂" },
            { id: "g19", type: "emoji", value: "💅" },
            { id: "g20", type: "emoji", value: "🤷" },
        ],
    },
    {
        id: "animals",
        label: "Animals",
        icon: "🐶",
        stickers: [
            { id: "a1", type: "emoji", value: "🐶" },
            { id: "a2", type: "emoji", value: "🐱" },
            { id: "a3", type: "emoji", value: "🐻" },
            { id: "a4", type: "emoji", value: "🐼" },
            { id: "a5", type: "emoji", value: "🦊" },
            { id: "a6", type: "emoji", value: "🐸" },
            { id: "a7", type: "emoji", value: "🐧" },
            { id: "a8", type: "emoji", value: "🦁" },
            { id: "a9", type: "emoji", value: "🐯" },
            { id: "a10", type: "emoji", value: "🐨" },
            { id: "a11", type: "emoji", value: "🦄" },
            { id: "a12", type: "emoji", value: "🐙" },
            { id: "a13", type: "emoji", value: "🦋" },
            { id: "a14", type: "emoji", value: "🐢" },
            { id: "a15", type: "emoji", value: "🦆" },
            { id: "a16", type: "emoji", value: "🐝" },
            { id: "a17", type: "emoji", value: "🦀" },
            { id: "a18", type: "emoji", value: "🐬" },
            { id: "a19", type: "emoji", value: "🦭" },
            { id: "a20", type: "emoji", value: "🦔" },
        ],
    },
    {
        id: "food",
        label: "Food",
        icon: "🍕",
        stickers: [
            { id: "f1", type: "emoji", value: "🍕" },
            { id: "f2", type: "emoji", value: "🍔" },
            { id: "f3", type: "emoji", value: "🍜" },
            { id: "f4", type: "emoji", value: "🍣" },
            { id: "f5", type: "emoji", value: "🍦" },
            { id: "f6", type: "emoji", value: "🎂" },
            { id: "f7", type: "emoji", value: "🍩" },
            { id: "f8", type: "emoji", value: "☕" },
            { id: "f9", type: "emoji", value: "🧋" },
            { id: "f10", type: "emoji", value: "🍺" },
            { id: "f11", type: "emoji", value: "🍓" },
            { id: "f12", type: "emoji", value: "🥑" },
            { id: "f13", type: "emoji", value: "🌮" },
            { id: "f14", type: "emoji", value: "🍿" },
            { id: "f15", type: "emoji", value: "🧁" },
            { id: "f16", type: "emoji", value: "🥐" },
            { id: "f17", type: "emoji", value: "🍱" },
            { id: "f18", type: "emoji", value: "🥟" },
            { id: "f19", type: "emoji", value: "🍛" },
            { id: "f20", type: "emoji", value: "🫖" },
        ],
    },
    {
        id: "celebration",
        label: "Celebrate",
        icon: "🎉",
        stickers: [
            { id: "c1", type: "emoji", value: "🎉" },
            { id: "c2", type: "emoji", value: "🎊" },
            { id: "c3", type: "emoji", value: "🥂" },
            { id: "c4", type: "emoji", value: "🎁" },
            { id: "c5", type: "emoji", value: "🏆" },
            { id: "c6", type: "emoji", value: "🎯" },
            { id: "c7", type: "emoji", value: "🎮" },
            { id: "c8", type: "emoji", value: "🎸" },
            { id: "c9", type: "emoji", value: "🎵" },
            { id: "c10", type: "emoji", value: "🔥" },
            { id: "c11", type: "emoji", value: "⚡" },
            { id: "c12", type: "emoji", value: "💥" },
            { id: "c13", type: "emoji", value: "✨" },
            { id: "c14", type: "emoji", value: "💫" },
            { id: "c15", type: "emoji", value: "🌟" },
            { id: "c16", type: "emoji", value: "💎" },
            { id: "c17", type: "emoji", value: "🚀" },
            { id: "c18", type: "emoji", value: "🌈" },
            { id: "c19", type: "emoji", value: "❤️" },
            { id: "c20", type: "emoji", value: "💯" },
        ],
    },
];
